### PR TITLE
[Ainura_Task] completed

### PR DESCRIPTION
**Pull request by AinuraOrozobaeva**
Hi Nafisa,
My Task is ready

### CODE REVIEW

**Review by nsaodat — CHANGES_REQUESTED** [review]
Thanks Ainura!

Could you please fix few bugs in  toString method in your code. I have inserted the outputs from the Object class below for your info.
Many thanks.

public class ItemObjects {
    public static void main(String[] args) {

        Item item = new Item("Apple", 2.3, 20);

        System.out.println( item.calcCost()); // 46.0
        System.out.println(item); // Item{name='Apple', unitPrice=2.3, quantity= $20, total price= $20}
    }
}

**Comment by AinuraOrozobaeva** [comment]
Hi Nafisa,
I have done and pushed me new changes

**Comment by AinuraOrozobaeva** [comment]
Hi Nafisa,

I did the changes , thank you so much.

**Review by nsaodat — APPROVED** [review]

**Comment by nsaodat** [comment]
Ainura's task complete

**Pull request merged**
